/* 

     Other classes deal with Directory, FileNames/PathNames

     rev .001   2/21/96
            portable(?) handle-based class for files.
            open
            close
            create
            delete
            get_ (size, date, etc)
  
************************************************************************/
#include "usual.h"
/* #include "redbox.h" */
#include "mylib.h"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>        /* need strcpy  */
#include <memory.h>        /* memcpy   */

#include "test.h"



