//
//        WINDOW.H
#ifndef WINDOW_H
#define WINDOW_H

//#ifndef TOW_H
//#include "tow.h"
//#endif

void window_redraw_all(void);   /* WDISP  */
void screen_swap (void);

                                       /* implemented in WDISP.C */
//void draw_screen (twocorner* box);

                                 /* BWIND  */
//void print_string (window_t w_v, SHORT row, SHORT col, char const* s);

#endif
